### ISSUE TITLE
Error when installing GPy on a new machine with Amazon Linux. Error in compilation

### ISSUE THREAD

**Issue by beeva-ricardoguerrero** [SheffieldML/GPy#632]
A couple of weeks ago it worked just doing 
```pip-3.6 install GPy```
 but it's not working  anymore. It returns me this message

```
    building 'GPy.kern.src.stationary_cython' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/GPy
    creating build/temp.linux-x86_64-3.6/GPy/kern
    creating build/temp.linux-x86_64-3.6/GPy/kern/src
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/local/lib64/python3.6/site-packages/numpy/core/include -I. -I/usr/include/python3.6m -c GPy/kern/src/stationary_cython.c -o build/temp.linux-x86_64-3.6/GPy/kern/src/stationary_cython.o -fopenmp -O3
    In file included from /usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1816:0,
                     from /usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:18,
                     from /usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from GPy/kern/src/stationary_cython.c:242:
    /usr/local/lib64/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it by " \
      ^~~~~~~
    In file included from GPy/kern/src/stationary_cython.c:244:0:
    GPy/kern/src/stationary_utils.h:2:10: fatal error: omp.h: No such file or directory
     #include <omp.h>
              ^~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tbgbp_0t/GPy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-2_qnrgxj-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-tbgbp_0t/GPy/
```

I tried with
```
pip-3.6 install GPy==1.9.2
pip-3.6 install GPy==1.8.5
```
obtaining the same result.
Any idea?

Thanks

**Comment by beeva-ricardoguerrero** [comment]
Extra info:

In my local (Ubuntu 14.04, gcc 6.3.0) works OK
in a AWS machine using Ubuntu 16.04 and gcc 5.4.0 works OK 
but in an AWS machine with Amazon Linux (Redhat 7.2)  with gcc 7.3.1 doesn't work

**Comment by zhenwendai** [comment]
It seems that the problem is that the gcc does not have openmp support, maybe try another version of gcc with openmp.

**Comment by gobbleturk** [comment]
I was able to solve this problem by using an older version of gcc. I first uninstalled my current version (7.2):
`sudo yum remove gcc`
Then I installed an older version:
`sudo yum install gcc-gfortran.noarch` (this is version 4.8)

**Comment by gerner** [comment]
I got this to work with gcc 6.4, but not with gcc 7.2. In particular these were my steps to fix:

```
sudo yum install -y gcc64-c++.x86_64
sudo update-alternatives --set gcc /usr/bin/gcc64
```

I'm not sure why this doesn't work with gcc 7.2 on Amazon Linux. If it helps or is relevant this is on a SageMaker Notebook instance.

**Comment by gerner** [comment]
this SO thread seems relevant: https://stackoverflow.com/questions/53094032/fopenmp-does-not-include-omp-h-on-amazon-linux/54111148#54111148

in particular this comment: https://stackoverflow.com/questions/53094032/fopenmp-does-not-include-omp-h-on-amazon-linux/54111148#comment95116279_54111148

> Currently, we can install three versions of gcc from yum repository on Amazon Linux. Gcc 4.8 and 6.4 are compiled with libgomp, but 7.2 is not. I don't know why 7.2 is not compiled with libgomp. I assume that both 4.8 and 7.2 are installed in Gravin's instance, so -fopenmp option fails. – S. Takezawa
