### ISSUE TITLE
Python setup.py build_ext --inplace fails on Windows with Python 3.7.1

### ISSUE THREAD

**Issue by joseortiz3** [SheffieldML/GPy#713]
I'm getting a bunch of `stationary_cython.c` errors when manually installing on Windows 10 Pro, VS 2017, VC 2017 compiler (same errors occur with pip install).

OS: Windows 10 Pro
Python: 3.7.1
Scipy: 1.1.0
Numpy: 1.15.3
Compiler: MSVC 14.16.27023
WinSDK: 10.0.17763.0

```Javascript
Joey@DEEPTHOUGHT MINGW64 ~/Downloads/GPy (devel)
$ git checkout devel
Already on 'devel'
Your branch is up to date with 'origin/devel'.

Joey@DEEPTHOUGHT MINGW64 ~/Downloads/GPy (devel)
$ python setup.py build_ext --inplace
running build_ext
building 'GPy.kern.src.stationary_cython' extension
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\Joey\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\include -I. -IC:\Users\Joey\AppData\Local\Programs\Python\Python37\include -IC:\Users\Joey\AppData\Local\Programs\Python\Python37\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /TcGPy/kern/src/stationary_cython.c /Fobuild\temp.win-amd64-3.7\Release\GPy/kern/src/stationary_cython.obj -fopenmp -O3
cl : Command line warning D9002 : ignoring unknown option '-fopenmp'
cl : Command line warning D9002 : ignoring unknown option '-O3'
stationary_cython.c
c:\users\joey\appdata\local\programs\python\python37\lib\site-packages\numpy\core\include\numpy\npy_1_7_deprecated_api.h(12) : Warning Msg: Using deprecated NumPy API, disable it by #defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
GPy/kern/src/stationary_cython.c(19389): error C2039: 'exc_type': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19390): error C2039: 'exc_value': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19391): error C2039: 'exc_traceback': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19403): error C2039: 'exc_type': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19404): error C2039: 'exc_value': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19405): error C2039: 'exc_traceback': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19406): error C2039: 'exc_type': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19407): error C2039: 'exc_value': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19408): error C2039: 'exc_traceback': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19451): error C2039: 'exc_type': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19452): error C2039: 'exc_value': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19453): error C2039: 'exc_traceback': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19454): error C2039: 'exc_type': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19455): error C2039: 'exc_value': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19456): error C2039: 'exc_traceback': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19478): error C2039: 'exc_type': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19479): error C2039: 'exc_value': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19480): error C2039: 'exc_traceback': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19481): error C2039: 'exc_type': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19482): error C2039: 'exc_value': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
GPy/kern/src/stationary_cython.c(19483): error C2039: 'exc_traceback': is not a member of '_ts'
c:\users\joey\appdata\local\programs\python\python37\include\pystate.h(212): note: see declaration of '_ts'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2

Joey@DEEPTHOUGHT MINGW64 ~/Downloads/GPy (devel)
$ python -m pip install numpy
Requirement already satisfied: numpy in c:\users\joey\appdata\local\programs\python\python37\lib\site-packages (1.15.3)

Joey@DEEPTHOUGHT MINGW64 ~/Downloads/GPy (devel)
$ python -m pip install scipy
Requirement already satisfied: scipy in c:\users\joey\appdata\local\programs\python\python37\lib\site-packages (1.1.0)
Requirement already satisfied: numpy>=1.8.2 in c:\users\joey\appdata\local\programs\python\python37\lib\site-packages (from scipy) (1.15.3)
```

Ultimately, I am looking for a t-distributed process package for python.

**Comment by mzwiessele** [comment]
Due to some compilation issues, we still don’t support py37 I’m afraid...

**Comment by joseortiz3** [comment]
Well, that solves the issue @mzwiessele. Works on 3.6.6

**Comment by apaleyes** [comment]
An update on this thread: #719 fixed things for GPy itself, but not the whole install story. I've tried to install GPy from source on Python 3.7, and got stuck at paramz dependency. Error:

```
...
Running paramz-0.9.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-s39hq94t/paramz-0.9.4/egg-dist-tmp-n6ewnxbm
...
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
...
  File "/usr/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 416, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```

Judging by this [SO thread](https://stackoverflow.com/questions/30861493/how-to-fix-python-valueerrorbad-marshal-data) it seems paramz binaries are somehow incompatible with Python 3.7.

Did anyone have success installing GPy after #719 was merged?
