### ISSUE TITLE
GPy 1.10.0 is not compatible with numpy 1.26.x  on python 3.10.0

### ISSUE THREAD

**Issue by rameezdev** [SheffieldML/GPy#1050]
Error

C:\Users\rameezra>pip install GPy==1.10.0
Collecting GPy==1.10.0
  Using cached GPy-1.10.0.tar.gz (959 kB)
Collecting numpy>=1.7
  Using cached numpy-1.26.2-cp310-cp310-win_amd64.whl (15.8 MB)
Requirement already satisfied: six in c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages (from GPy==1.10.0) (1.16.0)
Requirement already satisfied: paramz>=0.9.0 in c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages (from GPy==1.10.0) (0.9.5)
Requirement already satisfied: cython>=0.29 in c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages (from GPy==1.10.0) (3.0.6)
Requirement already satisfied: scipy>=1.3.0 in c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages (from GPy==1.10.0) (1.11.4)
Requirement already satisfied: decorator>=4.0.10 in c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages (from paramz>=0.9.0->GPy==1.10.0) (5.1.1)
Using legacy 'setup.py install' for GPy, since package 'wheel' is not installed.
Installing collected packages: numpy, GPy
    Running setup.py install for GPy ... done
Successfully installed GPy-1.10.0 numpy-1.26.2
WARNING: You are using pip version 21.2.3; however, version 23.3.1 is available.
You should consider upgrading via the 'C:\Users\rameezra\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

C:\Users\rameezra>python
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import GPy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rameezra\AppData\Local\Programs\Python\Python310\lib\site-packages\GPy\__init__.py", line 32, in <module>
    from numpy.testing import Tester
ImportError: cannot import name 'Tester' from 'numpy.testing' (C:\Users\rameezra\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\testing\__init__.py)
>>> exit()

C:\Users\rameezra>pip list
Package    Version
---------- -------
Cython     3.0.6
decorator  5.1.1
GPy        1.10.0
graphviz   0.20.1
numpy      1.26.2
paramz     0.9.5
pip        21.2.3
pipdeptree 2.13.1
scipy      1.11.4
setuptools 57.4.0
six        1.16.0
WARNING: You are using pip version 21.2.3; however, version 23.3.1 is available.
You should consider upgrading via the 'C:\Users\rameezra\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

C:\Users\rameezra>pip uninstall numpy
Found existing installation: numpy 1.26.2
Uninstalling numpy-1.26.2:
  Would remove:
    c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages\numpy-1.26.2-cp310-cp310-win_amd64.whl
    c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages\numpy-1.26.2.dist-info\*
    c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages\numpy.libs\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dll
    c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages\numpy\*
    c:\users\rameezra\appdata\local\programs\python\python310\scripts\f2py.exe
Proceed (Y/n)? y
  Successfully uninstalled numpy-1.26.2

C:\Users\rameezra>pip install numpy==1.26.1
Collecting numpy==1.26.1
  Downloading numpy-1.26.1-cp310-cp310-win_amd64.whl (15.8 MB)
     |████████████████████████████████| 15.8 MB 1.3 MB/s
Installing collected packages: numpy
Successfully installed numpy-1.26.1
WARNING: You are using pip version 21.2.3; however, version 23.3.1 is available.
You should consider upgrading via the 'C:\Users\rameezra\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

C:\Users\rameezra>python
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import GPy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rameezra\AppData\Local\Programs\Python\Python310\lib\site-packages\GPy\__init__.py", line 32, in <module>
    from numpy.testing import Tester
ImportError: cannot import name 'Tester' from 'numpy.testing' (C:\Users\rameezra\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\testing\__init__.py)
>>> exit()

C:\Users\rameezra>pip uninstall numpy
Found existing installation: numpy 1.26.1
Uninstalling numpy-1.26.1:
  Would remove:
    c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages\numpy-1.26.1-cp310-cp310-win_amd64.whl
    c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages\numpy-1.26.1.dist-info\*
    c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages\numpy.libs\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dll
    c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages\numpy\*
    c:\users\rameezra\appdata\local\programs\python\python310\scripts\f2py.exe
Proceed (Y/n)? y
  Successfully uninstalled numpy-1.26.1

C:\Users\rameezra>pip install numpy==1.26.0
Collecting numpy==1.26.0
  Downloading numpy-1.26.0-cp310-cp310-win_amd64.whl (15.8 MB)
     |████████████████████████████████| 15.8 MB 2.2 MB/s
Installing collected packages: numpy
Successfully installed numpy-1.26.0
WARNING: You are using pip version 21.2.3; however, version 23.3.1 is available.
You should consider upgrading via the 'C:\Users\rameezra\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

C:\Users\rameezra>python
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import GPy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rameezra\AppData\Local\Programs\Python\Python310\lib\site-packages\GPy\__init__.py", line 32, in <module>
    from numpy.testing import Tester
ImportError: cannot import name 'Tester' from 'numpy.testing' (C:\Users\rameezra\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\testing\__init__.py)
>>> exit()

C:\Users\rameezra>pip uninstall numpy
Found existing installation: numpy 1.26.0
Uninstalling numpy-1.26.0:
  Would remove:
    c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages\numpy-1.26.0-cp310-cp310-win_amd64.whl
    c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages\numpy-1.26.0.dist-info\*
    c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages\numpy.libs\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-65e29aac85b9409a6008e2dc84b1cc09.dll
    c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages\numpy\*
    c:\users\rameezra\appdata\local\programs\python\python310\scripts\f2py.exe
Proceed (Y/n)? y
  Successfully uninstalled numpy-1.26.0

C:\Users\rameezra>pip install numpy==1.25.2
Collecting numpy==1.25.2
  Downloading numpy-1.25.2-cp310-cp310-win_amd64.whl (15.6 MB)
     |████████████████████████████████| 15.6 MB 1.7 MB/s
Installing collected packages: numpy
Successfully installed numpy-1.25.2
WARNING: You are using pip version 21.2.3; however, version 23.3.1 is available.
You should consider upgrading via the 'C:\Users\rameezra\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

C:\Users\rameezra>python
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import GPy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rameezra\AppData\Local\Programs\Python\Python310\lib\site-packages\GPy\__init__.py", line 32, in <module>
    from numpy.testing import Tester
ImportError: cannot import name 'Tester' from 'numpy.testing' (C:\Users\rameezra\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\testing\__init__.py)
>>> exit()

C:\Users\rameezra>pipdeptree
GPy==1.10.0
├── Cython [required: >=0.29, installed: 3.0.6]
├── numpy [required: >=1.7, installed: 1.25.2]
├── paramz [required: >=0.9.0, installed: 0.9.5]
│   ├── decorator [required: >=4.0.10, installed: 5.1.1]
│   ├── numpy [required: >=1.7, installed: 1.25.2]
│   ├── scipy [required: Any, installed: 1.11.4]
│   │   └── numpy [required: >=1.21.6,<1.28.0, installed: 1.25.2]
│   └── six [required: Any, installed: 1.16.0]
├── scipy [required: >=1.3.0, installed: 1.11.4]
│   └── numpy [required: >=1.21.6,<1.28.0, installed: 1.25.2]
└── six [required: Any, installed: 1.16.0]
graphviz==0.20.1
pip==21.2.3
pipdeptree==2.13.1
setuptools==57.4.0

**Comment by rameezdev** [comment]
working with numpy 1.23.0

C:\Users\rameezra>pip uninstall numpy
Found existing installation: numpy 1.25.2
Uninstalling numpy-1.25.2:
  Would remove:
    c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages\numpy-1.25.2.dist-info\*
    c:\users\rameezra\appdata\local\programs\python\python310\lib\site-packages\numpy\*
    c:\users\rameezra\appdata\local\programs\python\python310\scripts\f2py.exe
Proceed (Y/n)? y
  Successfully uninstalled numpy-1.25.2

C:\Users\rameezra>pip install numpy==1.23.0
Collecting numpy==1.23.0
  Downloading numpy-1.23.0-cp310-cp310-win_amd64.whl (14.6 MB)
     |████████████████████████████████| 14.6 MB 2.2 MB/s
Installing collected packages: numpy
Successfully installed numpy-1.23.0
WARNING: You are using pip version 21.2.3; however, version 23.3.1 is available.
You should consider upgrading via the 'C:\Users\rameezra\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

C:\Users\rameezra>python
Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import GPy
>>>

**Comment by MartinBubel** [comment]
This is adressed in develop but there is no release covering it yet. There will be a new release soon, incl. python3.10 support etc.

Potential workaround for now: Use GPy as a git-dependency on branch develop.

I will close the issue as it is already adressed. Feel free to open if the issue persists or you can difficulties with applying the proposed workaround.
